config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "books#index"
  resources :books, only: [:index, :new, :create, :destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  with_options presence: true do
    validates :title
    validates :image
    validates :author
    validates :date
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books

  with_options presence: true do
    validates :nickname
    validates :email, uniqueness: true
    validates :password, length: { minimum: 6 },
                         format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :image, :introduce])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.valid?
      @book.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to root_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :discription, :date, :image).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="contents row">
  <div class="container">
   <h2>編集する</h2>
   <%= form_with(model: @book, local: true) do |f| %>
      <%= f.label :title, "タイトル" %>
      <p><%= f.text_field :title %></p>
      <%= f.label :image, "画像" %>
      <p><%= f.file_field :image %></p>
      <%= f.label :author, "作者" %>
      <p><%= f.text_field :author %></p>
      <%= f.label :description, "感想"%>
      <p><%= f.text_area :description %></p>
      <%= f.label :date, "日付" %>
      <p><%= f.date_field :date %></p>
      <%= f.submit "登録" %>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<div class="contents row">
  <div class="container">
      <%= @books.each do |book| %>
        <div class="colum is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-">
                <%= image_tag book.image if book.image.attached? %>
              </figure>
            </div>
            <div class="card-title">
              <span><%= book.title %><br><%= book.author %></span>
               <br><%= link_to '編集', edit_book_path(book.id), method: :get %>
               <br><%= link_to '削除', book_path(book.id), method: :delete %>
            </div>
          </div>
       </div>
      <% end %>
      <p><%= link_to "読んだ本を登録する", new_book_path %></p>
    </div>
  </div>
</section>

app/views/books/new.html.erb
<div class="contents row">
  <div class="container">
   <h2>読んだ本を登録する</h2>
   <%= form_with(model: @book, local: true) do |f| %>
      <%= f.label :title, "タイトル" %>
      <p><%= f.text_field :title %></p>
      <%= f.label :image, "画像" %>
      <p><%= f.file_field :image %></p>
      <%= f.label :author, "作者" %>
      <p><%= f.text_field :author %></p>
      <%= f.label :description, "感想"%>
      <p><%= f.text_area :description %></p>
      <%= f.label :date, "日付" %>
      <p><%= f.date_field :date %></p>
      <%= f.submit "登録" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hontomo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar is-success">
     <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: cursive;">ほんとも</h1>
        <% end %>
     </div>
     <% if user_signed_in? %>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "#{current_user.nickname}のページ", "/users/#{current_user.id}", class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
       </div>
      </div>
    </header>
    <%= yield %>
    <footer>
    </footer>
  </body>
</html>